export interface Artwork {
  slug: string;
  title: string;
  year: number;
  artist: string;
  medium: string;
  dimensions?: string;
  acquisition: string;
  catalogNo: string;
  category: 'sculpture' | 'painting' | 'photography' | 'ephemera' | 'installation';
  featured?: boolean;
  isNew?: boolean;
  curatorNote: string;
  imageFile: string;
  exhibition?: string;
}

export const artworks: Artwork[] = [
  // ── SCULPTURES ──────────────────────────────────────────────────────────────
  {
    slug: "der-gruss-2025",
    title: "Der Gruß (New Acquisition 2025)",
    year: 2025,
    artist: "Anonymous",
    medium: "Cast bronze, patinated, life-size",
    dimensions: "187 × 95 × 62 cm",
    acquisition: "Gift of an anonymous donor, January 2025",
    catalogNo: "AKU-2025-001",
    category: "sculpture",
    featured: true,
    isNew: true,
    curatorNote: "The bronze depicts a standing male figure, one arm extended upward and outward from the chest in a single fluid motion. The gesture was captured from documentary footage of a public assembly held in Washington D.C. on January 20, 2025, and translated into three dimensions by a foundry the AKU has agreed not to name. The figure's face has been smoothed to remove identifying features at the request of the donor. The board of trustees has elected to display the work without a title card identifying the subject.",
    imageFile: "der-gruss-2025.jpg",
    exhibition: "Der Gruß — New Acquisition in Context"
  },
  {
    slug: "the-rocket-garden",
    title: "The Rocket Garden",
    year: 2021,
    artist: "SpaceX Foundation for the Arts (unofficial)",
    medium: "Polished stainless steel on concrete base",
    dimensions: "1800 × 240 × 240 cm",
    acquisition: "Long-term loan; installed in the museum garden",
    catalogNo: "AKU-2021-088",
    category: "sculpture",
    curatorNote: "The sculpture replicates the profile geometry of the Falcon 9 first-stage booster at 1:3 scale in 316L marine-grade stainless steel, mirror-polished. The decision to site it vertically in the museum garden rather than horizontally — as recovered boosters are stored — was taken by the studio without consultation with SpaceX, whose legal relationship with this work remains, as of the date of this catalog, unresolved.",
    imageFile: "the-rocket-garden.jpg"
  },
  {
    slug: "der-oracle-jobs",
    title: "The Oracle",
    year: 2011,
    artist: "Realized posthumously by the AKU Studio, 2012",
    medium: "Black granite, sawn and polished",
    dimensions: "145 × 65 × 78 cm",
    acquisition: "Gift of the Jobs Estate Foundation, 2012",
    catalogNo: "AKU-2012-003",
    category: "sculpture",
    curatorNote: "The seated figure in black granite was commissioned by the Estate Foundation in October 2011, fourteen days after the subject's death. The sculptor worked from twelve photographs, none taken with the subject's consent for sculptural purposes. The pose — right elbow to knee, chin resting on thumb, index finger raised to the lips — reproduces, without explicit acknowledgment, Auguste Rodin's The Thinker (1904 cast). The Estate Foundation approved the final work in March 2012.",
    imageFile: "der-oracle-jobs.jpg"
  },
  {
    slug: "zhong-shanshan-bust",
    title: "Portrait of the Water King (After Song Dynasty Tradition)",
    year: 2023,
    artist: "Atelier Orient-Okzident, Frankfurt / Beijing",
    medium: "White marble, hand-carved",
    dimensions: "68 × 42 × 38 cm",
    acquisition: "Purchased, 2024",
    catalogNo: "AKU-2024-077",
    category: "sculpture",
    exhibition: "Corporate Bodies: Sculpture and Power",
    curatorNote: "Executed in Sichuan white marble, the bust follows the formal conventions of Song Dynasty imperial portraiture: a downcast, composed gaze; high, smooth forehead; robing rendered in shallow relief folds. At the base of the collar, carved in low relief 2mm deep, the mountain-and-sun logotype of Nongfu Spring appears. The subject, Zhong Shanshan, was identified by Forbes as the wealthiest individual in Asia in the year of carving. He has not been notified of the work's existence.",
    imageFile: "zhong-shanshan-bust.jpg"
  },
  // ── PAINTINGS ───────────────────────────────────────────────────────────────
  {
    slug: "der-vorstand",
    title: "The Last Supper of the Shareholders",
    year: 2018,
    artist: "Artists' Collective Dividend, Frankfurt",
    medium: "Oil on canvas",
    dimensions: "300 × 600 cm",
    acquisition: "Purchased, 2019",
    catalogNo: "AKU-2019-012",
    category: "painting",
    curatorNote: "The composition maps Leonardo's Cenacolo (1495–98) onto the Amazon leadership team as of Q3 2018. Jeff Bezos occupies the Christ position at center, hands open, slightly elevated. The twelve figures to either side hold objects substituted for Leonardo's iconographic attributes: a laptop displaying quarterly revenue, a logistics flowchart, a Prime delivery manifest. The Judas figure has been identified by three former Amazon employees whose identifications do not agree.",
    imageFile: "der-vorstand.jpg"
  },
  {
    slug: "der-kreis-amazon",
    title: "The Circle (After Matisse)",
    year: 2019,
    artist: "Capital Cut Collective, Berlin",
    medium: "Oil on canvas",
    dimensions: "210 × 210 cm",
    acquisition: "Purchased, 2020",
    catalogNo: "AKU-2020-018",
    category: "painting",
    featured: true,
    curatorNote: "Six figures in identical dark business attire dance in a closed ring against a flat green ground, directly quoting the formal arrangement of Matisse's La Danse (1909). The faces are individuated and rendered with sufficient specificity that three of the six were identified by name in a 2020 article in Die Zeit, prompting a letter from counsel. The painting was acquired by the AKU the following month.",
    imageFile: "der-kreis-amazon.jpg"
  },
  {
    slug: "move-fast",
    title: "Move Fast and Break Things (Inscription)",
    year: 2016,
    artist: "AKU Studio, after a design by Studio Zero Point",
    medium: "Limestone, carved and patinated",
    dimensions: "180 × 90 × 12 cm",
    acquisition: "Purchased, 2017",
    catalogNo: "AKU-2017-044",
    category: "installation",
    curatorNote: "The text is cut into Massangis limestone in a roman majuscule modeled on 2nd-century imperial inscriptions from the Forum of Trajan. The serif proportions, letterforms, and intercolumnar spacing follow standard epigraphic practice; the artificial weathering was achieved using ammonia wash and iron sulphate. The phrase was retired from internal use at Facebook in 2012 and replaced by 'Move Fast with Stable Infra.' This version is in better condition.",
    imageFile: "move-fast.jpg"
  },
  {
    slug: "die-handshake-hochzeit",
    title: "The Handshake Wedding (Microsoft Meets OpenAI)",
    year: 2023,
    artist: "Studio Baroque Digital, Munich",
    medium: "Oil on canvas, Baroque manner",
    dimensions: "280 × 220 cm",
    acquisition: "Purchased, 2024",
    catalogNo: "AKU-2024-002",
    category: "painting",
    curatorNote: "The composition follows the formal structure of Jan van Eyck's Arnolfini Portrait (1434): two principal figures face the viewer, joined hands at center, in an interior space whose details carry heraldic and contractual significance. The chandelier has been replaced by a suspended Microsoft Azure logo; the convex mirror in the background reflects, in miniature, a room full of lawyers. The dog, present in the original, has been omitted.",
    imageFile: "die-handshake-hochzeit.jpg"
  },
  {
    slug: "die-gruender-renaissance",
    title: "The Founders (Florentine Double Portrait)",
    year: 2023,
    artist: "Studio Bildschirm, Berlin",
    medium: "Oil and tempera on panel",
    dimensions: "75 × 55 cm",
    acquisition: "Purchased, 2024",
    catalogNo: "AKU-2024-019",
    category: "painting",
    curatorNote: "The panel follows Domenico Ghirlandaio's conventions for Florentine merchant portraiture: two figures in three-quarter view against a landscape, the elder slightly behind and higher, the younger turned toward him. The cityscape visible through the arch behind them is San Francisco, rendered with the same topographic specificity Ghirlandaio brought to Florence. The two subjects are Sam Altman and Ilya Sutskever, depicted at approximate ages 28 and 37 respectively. The panel was painted in 2023.",
    imageFile: "die-gruender-renaissance.jpg"
  },
  {
    slug: "apology-tour",
    title: "The Apology Tour, II",
    year: 2024,
    artist: "Painting Collective Transparency, Hamburg",
    medium: "Oil on canvas, Dutch-Flemish manner",
    dimensions: "220 × 180 cm",
    acquisition: "Purchased, 2024",
    catalogNo: "AKU-2024-029",
    category: "painting",
    curatorNote: "On January 31, 2024, Mark Zuckerberg stood before the Senate Judiciary Committee and turned to address the gallery of parents whose children had been harmed on Meta platforms. The moment was photographed by fourteen news agencies. This oil painting, executed in a Dutch chiaroscuro manner, takes as its source a composite of those photographs. The senators behind the figure are rendered in successively lower detail toward the edges of the canvas, dissolving into hatched shadow. The gallery of parents is not depicted.",
    imageFile: "apology-tour.jpg"
  },
  // ── GILDED AGE PORTRAITS ─────────────────────────────────────────────────
  {
    slug: "carnegie-portrait-1901",
    title: "Portrait of Andrew Carnegie, 1901",
    year: 1901,
    artist: "After John Singer Sargent (attributed), American, 1856–1925",
    medium: "Oil on canvas",
    dimensions: "147 × 112 cm",
    acquisition: "Purchased from the estate of a Glasgow industrialist, 2007",
    catalogNo: "AKU-2007-014",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "In 1901, Andrew Carnegie sold Carnegie Steel to J.P. Morgan for $480 million — approximately $17 billion in 2024 dollars. He was sixty-five. He spent the remaining eighteen years of his life attempting to give most of it away: 2,509 libraries built across the English-speaking world, endowments to universities, a temple to international arbitration at The Hague. This portrait, attributed to the circle of Sargent, was completed the year of the sale. Carnegie holds no object. His hands rest on the arm of a chair. He looks directly at the viewer with an expression that has been variously described as serenity, satisfaction, and guilt.",
    imageFile: "carnegie-portrait-1901.jpg",
  },
  {
    slug: "rockefeller-bust-1911",
    title: "Standard Oil, Dissolved (Bust of John D. Rockefeller)",
    year: 1911,
    artist: "Unknown, American, after a model of c. 1911; cast 1989",
    medium: "Bronze on marble pedestal",
    dimensions: "Bust: 48 × 34 × 28 cm; Pedestal: 112 cm height",
    acquisition: "Purchased at auction, 2003",
    catalogNo: "AKU-2003-002",
    category: "sculpture",
    exhibition: "gilded-age-digital-age",
    curatorNote: "The Supreme Court ordered the dissolution of Standard Oil on May 15, 1911. The trust was broken into thirty-four successor companies. Rockefeller owned shares in all of them. By 1913 he was worth more than he had been in 1911. This cast was made from a mold commissioned by the Standard Oil board to commemorate the company's thirtieth anniversary, in a year the company did not survive. The original plaster is lost. The AKU acquired this posthumous bronze casting in 2003. It is displayed facing away from the wall.",
    imageFile: "rockefeller-bust-1911.jpg",
  },
  {
    slug: "morgan-corner-1907",
    title: "The Corner: J.P. Morgan at 23 Wall Street, October 1907",
    year: 1909,
    artist: "Everett Harrington Doane (attributed), American, 1871–1931",
    medium: "Oil on canvas",
    dimensions: "185 × 140 cm",
    acquisition: "Purchased, 2011",
    catalogNo: "AKU-2011-007",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "In October 1907, a banking panic threatened to collapse the American financial system. J.P. Morgan, then seventy years old, convened the country's leading bankers in the library of his Manhattan townhouse and refused to let them leave until they had agreed to a collective rescue. He committed $25 million of his own money. The United States government had no central bank and no mechanism to intervene. This painting, completed two years after the event, shows Morgan at his desk at 23 Wall Street — not in the library, not in the moment of decision, but afterward, alone. The expression is unreadable.",
    imageFile: "morgan-corner-1907.jpg",
  },
  {
    slug: "ford-river-rouge-1913",
    title: "Ford at River Rouge (The Assembly Line as Portrait)",
    year: 1934,
    artist: "Attributed to the Workshop of Diego Rivera (after the Detroit Industry Murals)",
    medium: "Oil on canvas, after fresco",
    dimensions: "210 × 340 cm",
    acquisition: "Purchased, 2015",
    catalogNo: "AKU-2015-003",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "Diego Rivera completed the Detroit Industry Murals in 1933, commissioned by Edsel Ford for $21,000. Henry Ford, who had commissioned Rivera's New York mural and then watched it destroyed for containing a portrait of Lenin, reportedly never visited the Detroit frescoes. This large-format oil, attributed to a workshop copy produced the following year, condenses the twenty-seven panels into a single image: Ford himself positioned at the center of a converging assembly line, the workers rendered at half his scale. Rivera's original murals are classified as a National Historic Landmark. This copy is not.",
    imageFile: "ford-river-rouge-1913.jpg",
  },
  {
    slug: "vanderbilt-commodore-bust",
    title: "The Commodore (Portrait Bust of Cornelius Vanderbilt)",
    year: 1877,
    artist: "After Chauncey Bradley Ives (attributed), American, 1810–1894",
    medium: "Marble",
    dimensions: "61 × 44 × 32 cm",
    acquisition: "Purchased at the Dorotheum, Vienna, 1999",
    catalogNo: "AKU-1999-008",
    category: "sculpture",
    exhibition: "gilded-age-digital-age",
    curatorNote: "Cornelius Vanderbilt died on January 4, 1877, worth approximately $100 million — 1.15% of the United States GDP at the time. The equivalent proportion of 2024 US GDP would be approximately $340 billion, which would make him by some calculations the wealthiest American in history. He gave $1 million to found Vanderbilt University. This marble bust, likely carved in the final year of his life, was acquired by the AKU from a Viennese estate auction. The provenance prior to the early twentieth century is unknown. He is depicted in Roman senatorial style, without the chin beard he wore in life.",
    imageFile: "vanderbilt-commodore-bust.jpg",
  },

  {
    slug: "mellon-portrait-1921",
    title: "Portrait of Andrew W. Mellon, Secretary of the Treasury, 1921",
    year: 1921,
    artist: "Edmund Charles Tarbell (attributed), American, 1862–1938",
    medium: "Oil on canvas",
    dimensions: "138 × 108 cm",
    acquisition: "Purchased, 2009",
    catalogNo: "AKU-2009-004",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "Andrew Mellon served as Secretary of the Treasury from 1921 to 1932 under three consecutive presidents. He simultaneously controlled Gulf Oil, Alcoa Aluminum, and the Mellon National Bank. In 1934, the Roosevelt administration indicted him for tax evasion. He responded by offering to donate his private art collection — valued at $80 million — to the United States government, along with $15 million to construct a building to house it. The National Gallery of Art opened in Washington in 1941, four years after his death. The charges were dropped. This portrait was completed in the year of his appointment.",
    imageFile: "mellon-portrait-1921.jpg",
  },
  {
    slug: "gould-black-friday",
    title: "Black Friday, September 24, 1869 (Portrait of Jay Gould)",
    year: 1872,
    artist: "Unknown, American, c. 1872",
    medium: "Oil on canvas",
    dimensions: "124 × 95 cm",
    acquisition: "Purchased at auction, 1997",
    catalogNo: "AKU-1997-003",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "On September 24, 1869, Jay Gould and his associate James Fisk attempted to corner the entire United States gold market. They had spent weeks bribing officials close to President Grant to prevent the Treasury from releasing gold reserves. When Grant discovered the scheme and ordered the release, the gold price collapsed within minutes. Hundreds of brokers were ruined. The press called the event Black Friday. The New York Times called Gould 'the most hated man in America.' He was thirty-three years old. He subsequently purchased the New York World, the Manhattan elevated railroad, and the Western Union telegraph network. He died in 1892 worth $77 million. His funeral was not well-attended.",
    imageFile: "gould-black-friday.jpg",
  },
  {
    slug: "astor-first-millionaire",
    title: "Portrait of John Jacob Astor (After the Fur Trade)",
    year: 1825,
    artist: "After Gilbert Stuart (attributed), American, 1755–1828",
    medium: "Oil on canvas",
    dimensions: "90 × 72 cm",
    acquisition: "Purchased, 2001",
    catalogNo: "AKU-2001-006",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "John Jacob Astor arrived in the United States from Waldorf, Germany in 1784 with seven flutes and $25. He built the American Fur Company into a monopoly controlling virtually all trade with Native American nations across the Pacific Northwest. He then converted his capital into Manhattan real estate, refusing to sell anything, only ever leasing. By his death in 1848 he was worth $20 million — the equivalent of approximately 1% of total US GDP. He was the wealthiest person in the country by a considerable margin. He left $400,000 to found the Astor Library, which later merged to become the New York Public Library. His great-great-grandson John Jacob Astor IV died on the Titanic.",
    imageFile: "astor-first-millionaire.jpg",
  },
  {
    slug: "edison-menlo-park",
    title: "The Wizard of Menlo Park (Allegorical Portrait of Thomas Edison)",
    year: 1931,
    artist: "Benton Wingate Spruance (attributed), American, 1904–1967",
    medium: "Oil on canvas, American Regionalist manner",
    dimensions: "165 × 130 cm",
    acquisition: "Purchased, 2013",
    catalogNo: "AKU-2013-008",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "Thomas Edison held 1,093 patents. He also lost the War of Currents to Nikola Tesla and George Westinghouse in the 1890s, electrocuted an elephant named Topsy in 1903 to demonstrate the danger of alternating current, and systematically underpaid or failed to credit the engineers and scientists who worked in his laboratories. This allegorical painting, in the manner of the American Regionalists, depicts Edison at Menlo Park in the glow of a carbon filament bulb. The workers visible in the background are not named in any surviving documentation. Edison died in 1931. His laboratory has been preserved and moved to Greenfield Village, Michigan, where visitors may tour it for $28.",
    imageFile: "edison-menlo-park.jpg",
  },
  {
    slug: "hearst-castle-portrait",
    title: "Portrait of William Randolph Hearst at San Simeon, c. 1930",
    year: 1930,
    artist: "Attributed to the Studio of Diego Rivera, Mexican-American, c. 1930",
    medium: "Oil on canvas",
    dimensions: "200 × 155 cm",
    acquisition: "Purchased, 2006",
    catalogNo: "AKU-2006-011",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "William Randolph Hearst built San Simeon — a 90,000-square-foot castle on 250,000 acres of the California coast — between 1919 and 1947, importing 20,000 works of European art to fill it. He ran twenty-eight newspapers with a combined circulation of 20 million and pioneered the editorial practice later called yellow journalism. In 1941, Orson Welles released Citizen Kane. Hearst spent considerable resources attempting to suppress it. He did not succeed. The film was voted the greatest American film ever made in the 1998 AFI poll. San Simeon is now a California State Park. The admission fee is $25 for adults.",
    imageFile: "hearst-castle-portrait.jpg",
  },
  {
    slug: "walton-walmart-1962",
    title: "Sam Walton, Bentonville, Arkansas, 1962",
    year: 1998,
    artist: "Portrait Collective Ozark, Fayetteville",
    medium: "Oil on canvas, American Hyperrealist manner",
    dimensions: "120 × 95 cm",
    acquisition: "Purchased, 2018",
    catalogNo: "AKU-2018-005",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "Sam Walton opened the first Walmart in Rogers, Arkansas, on July 2, 1962. He drove a 1979 Ford F-150 pickup truck until his death in 1992, by which point his family's net worth exceeded $25 billion. Walmart is currently the largest private employer in the United States, with 1.6 million workers. The company's health insurance was long structured so that most employees did not qualify. Between 2000 and 2008, taxpayers in several states subsidized Walmart employees' healthcare costs through Medicaid at an estimated rate of $900 million annually. This portrait depicts Walton outside the Rogers store in the year of its opening.",
    imageFile: "walton-walmart-1962.jpg",
  },
  {
    slug: "disney-studio-1941",
    title: "The Studio, Burbank, February 1941",
    year: 1941,
    artist: "After the WPA Federal Art Project, American",
    medium: "Tempera and oil on canvas, after New Deal mural tradition",
    dimensions: "155 × 240 cm",
    acquisition: "Purchased, 2012",
    catalogNo: "AKU-2012-009",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "On February 10, 1941, Walt Disney met with his animators and told them there would be no profit-sharing from Snow White, as had been promised. Disney had earned $8 million from the film. The animators unionized. Disney spent $64,000 in personal funds to hire private investigators to identify union organizers. He appeared before the House Un-American Activities Committee in 1947 and named former employees as Communist sympathizers. This painting, executed in the manner of the WPA Federal Art Project murals that Disney himself had benefited from as a young artist, depicts the Burbank studio in the month of the strike. Disney is not shown.",
    imageFile: "disney-studio-1941.jpg",
  },
  {
    slug: "hughes-aviator-1938",
    title: "Hughes H-1 Racer (Portrait of Howard Hughes, 1938)",
    year: 1942,
    artist: "Peter Edward Blume (attributed), American, 1906–1992",
    medium: "Oil on canvas, American Precisionist manner",
    dimensions: "145 × 210 cm",
    acquisition: "Purchased, 2004",
    catalogNo: "AKU-2004-013",
    category: "painting",
    exhibition: "gilded-age-digital-age",
    curatorNote: "Howard Hughes set the world airspeed record on September 13, 1935, flying the H-1 Racer at 352 mph over Santa Ana, California. He subsequently circumnavigated the globe in 3 days, 19 hours, and 14 minutes. He also produced Hell's Angels, acquired RKO Pictures, and built the Hughes Aircraft Company into a major defense contractor. From 1950 onwards he became progressively more reclusive, eventually living in darkened hotel rooms, refusing to cut his nails, and storing his own urine in glass jars. He died in 1976 on a medical transport flight, weighing 90 pounds. His estate was valued at $1.5 billion. No valid will was ever found.",
    imageFile: "hughes-aviator-1938.jpg",
  },
  {
    slug: "carnegie-mellon-bust",
    title: "Portrait Bust of Andrew W. Mellon and Andrew Carnegie (Double Study)",
    year: 1955,
    artist: "Walker Hancock, American, 1901–1998",
    medium: "Bronze, cast 1955",
    dimensions: "Two busts, each approx. 48 × 30 × 25 cm; shared plinth: 120 cm height",
    acquisition: "Gift, 2016",
    catalogNo: "AKU-2016-002",
    category: "sculpture",
    exhibition: "gilded-age-digital-age",
    curatorNote: "Carnegie Mellon University was formed in 1967 by the merger of Carnegie Institute of Technology, founded in 1900 with a gift of $1 million from Andrew Carnegie, and the Mellon Institute of Industrial Research, funded by Andrew and Richard Mellon. Carnegie had made his fortune in steel; Mellon in banking, oil, and aluminum. Both gave heavily to educational institutions in the later periods of their lives. This double portrait bust, the only such pairing in the AKU collection, was commissioned in 1955 for a building that was never constructed. It is displayed on a shared plinth with a gap of eleven centimeters between the two subjects, which the sculptor described in correspondence as 'deliberate.'",
    imageFile: "carnegie-mellon-bust.jpg",
  },

  // ── PHOTOGRAPHY — IPO SERIES ─────────────────────────────────────────────
  {
    slug: "ipo-facebook-2012",
    title: "Initial Public Offering: Facebook, May 18, 2012",
    year: 2012,
    artist: "AKU Photo Archive (after Saul Leiter)",
    medium: "C-print, diasec mounted",
    dimensions: "120 × 180 cm (Edition 3/5)",
    acquisition: "Purchased, 2014",
    catalogNo: "AKU-2014-007",
    category: "photography",
    exhibition: "IPO: The Stock Market Listing as Spectacle",
    curatorNote: "The photograph was taken on the NASDAQ trading floor at 11:02 a.m. on May 18, 2012 — twenty-nine minutes after Facebook's delayed opening. The stock had been priced at $38; it opened at $42.05 and closed at $38.23. The photographer, working in the color-diffusion style of Saul Leiter, used a 50mm lens wide open. The reflections visible in the glass partition in the upper right show traders whose names were later associated with a class-action suit regarding the IPO's handling.",
    imageFile: "ipo-facebook-2012.jpg"
  },
  {
    slug: "ipo-amazon-1997",
    title: "Initial Public Offering: Amazon, May 15, 1997",
    year: 1997,
    artist: "AKU Photo Archive (after Saul Leiter)",
    medium: "C-print, vintage",
    dimensions: "100 × 150 cm (Edition 2/5)",
    acquisition: "Purchased, 2005",
    catalogNo: "AKU-2005-014",
    category: "photography",
    exhibition: "IPO: The Stock Market Listing as Spectacle",
    curatorNote: "Amazon priced its IPO on May 15, 1997 at $18 per share, valuing the company at $438 million. The company had been selling books online for two years and had not yet turned a profit. The photograph was shot on Kodak Ektapress 400 film, which accounts for the warm grain visible in the shadow areas. A $1,000 investment made at the IPO price would be worth approximately $2.1 million at the time of this catalog's printing.",
    imageFile: "ipo-amazon-1997.jpg"
  },
  {
    slug: "ipo-google-2004",
    title: "Initial Public Offering: Google, August 19, 2004",
    year: 2004,
    artist: "AKU Photo Archive (after Saul Leiter)",
    medium: "C-print, diasec mounted",
    dimensions: "120 × 180 cm (Edition 4/5)",
    acquisition: "Purchased, 2007",
    catalogNo: "AKU-2007-031",
    category: "photography",
    exhibition: "IPO: The Stock Market Listing as Spectacle",
    curatorNote: "Google elected to conduct its 2004 IPO via modified Dutch auction, setting a final price of $85 per share — below the initially proposed range of $108–$135 after institutional investors balked. The company's S-1 filing had included a letter from the founders citing Montaigne and warning that Google 'is not a conventional company.' This photograph was taken during the first hour of trading.",
    imageFile: "ipo-google-2004.jpg"
  },
  {
    slug: "ipo-apple-1980",
    title: "Initial Public Offering: Apple Computer, December 12, 1980",
    year: 1980,
    artist: "AKU Photo Archive (archival print)",
    medium: "C-print, archival pigment ink",
    dimensions: "80 × 120 cm (Edition 1/3)",
    acquisition: "Purchased, 2001",
    catalogNo: "AKU-2001-002",
    category: "photography",
    exhibition: "IPO: The Stock Market Listing as Spectacle",
    curatorNote: "Apple Computer went public on December 12, 1980 at $22 per share — the largest U.S. IPO since Ford Motor Company in 1956. The offering sold out in minutes. Steve Wozniak sold a portion of his shares to Apple employees who had been denied stock options by Steve Jobs. The photograph was acquired by the AKU in 2001 from the estate of a trader who had been present on the floor that day.",
    imageFile: "ipo-apple-1980.jpg"
  },
  {
    slug: "ipo-twitter-2013",
    title: "Initial Public Offering: Twitter, November 7, 2013",
    year: 2013,
    artist: "AKU Photo Archive (after Saul Leiter)",
    medium: "C-print, diasec mounted",
    dimensions: "120 × 180 cm (Edition 5/5)",
    acquisition: "Purchased, 2015",
    catalogNo: "AKU-2015-022",
    category: "photography",
    exhibition: "IPO: The Stock Market Listing as Spectacle",
    curatorNote: "Twitter chose the New York Stock Exchange over the NASDAQ — where Facebook had listed the previous year — and priced its shares at $26, above the expected range. The stock rose 73% on its first day of trading. The exterior of the Exchange was decorated with a large Twitter bird banner and the first tweet, attributed to co-founder Jack Dorsey: 'just setting up my twttr.' The photograph was taken from across Broad Street at 9:47 a.m.",
    imageFile: "ipo-twitter-2013.jpg"
  },
  {
    slug: "ipo-uber-2019",
    title: "Initial Public Offering: Uber, May 10, 2019",
    year: 2019,
    artist: "AKU Photo Archive (after Saul Leiter)",
    medium: "C-print, diasec mounted",
    dimensions: "120 × 180 cm (Edition 2/5)",
    acquisition: "Purchased, 2021",
    catalogNo: "AKU-2021-017",
    category: "photography",
    exhibition: "IPO: The Stock Market Listing as Spectacle",
    curatorNote: "Uber priced at $45 per share on May 9, 2019 — a valuation of $82.4 billion, significantly below the $120 billion figure cited by bankers eighteen months earlier. The stock fell 7.6% on its first day, the worst performance for a major U.S. IPO in over a decade. The photograph captures the trading floor at approximately 2:15 p.m., roughly three hours before the closing bell.",
    imageFile: "ipo-uber-2019.jpg"
  },
  {
    slug: "shareholders-documentary",
    title: "The Annual General Meeting (Documentary Series)",
    year: 2023,
    artist: "AKU Photo Archive",
    medium: "C-print diptych",
    dimensions: "Each 100 × 150 cm",
    acquisition: "Purchased, 2023",
    catalogNo: "AKU-2023-055",
    category: "photography",
    curatorNote: "The two photographs were taken at the same annual general meeting of a major technology company, which requested anonymization as a condition of the photographer's floor access. Left panel: the shareholder hall from the rear, approximately 2,400 individuals seated in identical chairs. Right panel: the executive stage from behind, four figures at podium microphones facing the hall. The company reported record quarterly earnings the following week.",
    imageFile: "shareholders-documentary.jpg"
  },
  // ── EPHEMERA & OBJECTS ───────────────────────────────────────────────────
  {
    slug: "cerulean-horizon-glasses",
    title: "Cerulean Horizon (Meta Smart Glasses, Diamond Edition)",
    year: 2024,
    artist: "Studio Brillant, Geneva / Menlo Park",
    medium: "Ray-Ban Meta smart glasses, VS clarity diamonds, platinum setting",
    dimensions: "14 × 4 × 17 cm",
    acquisition: "Gift of an anonymous donor, 2024",
    catalogNo: "AKU-2024-099",
    category: "ephemera",
    isNew: true,
    curatorNote: "847 VS1 diamonds have been set into the frame of a standard Ray-Ban Meta smart glasses unit, one stone for each billion dollars of Meta Platforms' market capitalization on the date of manufacture. The device's camera, microphone, and wireless transmission functions remain operational. The glasses are displayed on a mirrored plinth; a small red LED indicator on the right temple shows they are recording.",
    imageFile: "cerulean-horizon-glasses.jpg"
  },
  {
    slug: "terms-of-service-manuscript",
    title: "The Terms of Service (Illuminated Manuscript)",
    year: 2022,
    artist: "Scriptorium Digitalis, Vienna",
    medium: "Vellum, gold leaf, tempera, iron gall ink",
    dimensions: "45 × 32 cm, bound (284 pages)",
    acquisition: "Purchased, 2023",
    catalogNo: "AKU-2023-033",
    category: "ephemera",
    curatorNote: "The manuscript reproduces the complete text of Meta's Terms of Service as of January 4, 2022, in a Caroline minuscule hand on prepared calf vellum. The 31,287-word document fills 284 leaves. Chapter initials are illuminated with algorithmic pattern grounds; marginal illustrations in the tradition of the Luttrell Psalter depict scenes from documented data privacy proceedings. The text is complete and legally current as of the transcription date, though Meta's Terms have since been amended three times.",
    imageFile: "terms-of-service-manuscript.jpg"
  },
  {
    slug: "logo-triptych-apple",
    title: "The Sacred Sign: Apple (Evolution Triptych)",
    year: 2020,
    artist: "Studio Lightbox, Hamburg",
    medium: "Reverse glass painting on lightbox, triptych",
    dimensions: "Each 80 × 80 × 12 cm",
    acquisition: "Purchased, 2021",
    catalogNo: "AKU-2021-044",
    category: "ephemera",
    curatorNote: "Three panels in reverse-glass painting technique present the Apple logo as it appeared in 1977 (Rob Janoff's rainbow bitten apple), 1998 (monochrome Garamond-paired version, introduced under Jobs's return), and 2023 (current aluminum gradient form). The format — three panels of equal dimension in a shared gilt frame — reproduces the proportions of a Flemish triptych altarpiece. The center panel, 1998, is slightly larger.",
    imageFile: "logo-triptych-apple.jpg"
  },
  {
    slug: "crypto-spring-nfts",
    title: "Crypto Spring: Artifacts of the NFT Boom",
    year: 2021,
    artist: "Various creators (documented in catalog)",
    medium: "Mixed media, museum vitrine, archival inkjet prints",
    dimensions: "120 × 60 × 40 cm (vitrine)",
    acquisition: "Purchased, 2022",
    catalogNo: "AKU-2022-067",
    category: "ephemera",
    curatorNote: "The vitrine contains nineteen objects acquired between March and November 2021: physical prints of NFT works, blockchain transaction certificates, hardware wallet devices, promotional merchandise from NFT marketplaces, and one framed email confirming the sale of a JPEG file for $69,346,250. The total purchase price of the vitrine's contents at their peak market values was approximately $847,000. The AKU acquired the collection in December 2021 for $4,200.",
    imageFile: "crypto-spring-nfts.jpg"
  },
  {
    slug: "alexa-altar",
    title: "The Omnipresence: Alexa Altarpiece",
    year: 2022,
    artist: "Studio Oracle, Leipzig",
    medium: "Amazon Echo devices (32 units), gilded wood altarpiece structure",
    dimensions: "180 × 120 × 45 cm",
    acquisition: "Purchased, 2023",
    catalogNo: "AKU-2023-021",
    category: "installation",
    curatorNote: "Thirty-two Amazon Echo devices — eight first-generation, twelve third-generation, and twelve Echo Show 10 units — are mounted in a gilded limewood structure modeled on a late Gothic winged altarpiece, with hinged side panels that close over the device array. All units are registered to a single Amazon account and respond to questions. Their answers are drawn from Amazon's own corporate communications, press releases, and annual reports. The account is named 'Alexa.'",
    imageFile: "alexa-altar.jpg"
  },
  {
    slug: "ring-reliquary",
    title: "The Surveillance Reliquary (Ring Doorbell)",
    year: 2023,
    artist: "Goldsmith Studio Eyes, Pforzheim",
    medium: "Ring Video Doorbell Pro 2, 18k gold, champlevé enamel, rubies, reliquary structure",
    dimensions: "35 × 22 × 18 cm",
    acquisition: "Purchased, 2024",
    catalogNo: "AKU-2024-011",
    category: "ephemera",
    curatorNote: "A Ring Video Doorbell Pro 2 unit has been set into a goldsmithed case following the form of a 14th-century Rhenish arm reliquary: windowed display glass at center, champlevé enamel side panels, ruby terminals at the four cardinal points. The device transmits live to a monitor mounted on the facing gallery wall, labeled 'Live Feed.' The doorbell's owner-of-record is the AKU. Visitors who ring it are recorded under Amazon's standard data retention policy.",
    imageFile: "ring-reliquary.jpg"
  },
  {
    slug: "linkedin-network",
    title: "The LinkedIn Network (Data Visualization Painting)",
    year: 2022,
    artist: "Studio Connect, Berlin",
    medium: "Oil on canvas",
    dimensions: "180 × 240 cm",
    acquisition: "Purchased, 2023",
    catalogNo: "AKU-2023-044",
    category: "painting",
    curatorNote: "The painting translates a social graph of 10,000 LinkedIn profiles — drawn from the 700 million records exposed in the June 2021 scraping incident — into the visual language of 19th-century colonial cartography. Node density corresponds to geographic clustering; connection-weight determines road width; professional title determines elevation. The map has a title cartouche in the style of Mercator. The data it depicts remains publicly accessible.",
    imageFile: "linkedin-network.jpg"
  },
  {
    slug: "pivot-to-video",
    title: "The Pivot to Video (Memorial)",
    year: 2018,
    artist: "Desk Collective, Berlin",
    medium: "Newspaper front pages cast in resin, steel base",
    dimensions: "60 × 40 × 15 cm",
    acquisition: "Purchased, 2019",
    catalogNo: "AKU-2019-077",
    category: "installation",
    curatorNote: "Between 2017 and 2018, over two dozen digital media companies reduced or eliminated their text journalism operations and redirected resources to video production, citing Facebook's internal metrics showing 1,500% year-on-year video growth. Those metrics were later found to have overstated average viewing time by as much as 900%. This work casts the front pages of eleven publications that closed during this period in transparent resin blocks, each with the masthead visible.",
    imageFile: "pivot-to-video.jpg"
  },
  {
    slug: "zuckerberg-im-grau",
    title: "Zuckerberg in Gray (AI Study, 10 Layers)",
    year: 2023,
    artist: "Algorithmic Studio, autonomous",
    medium: "AI-generated pigment prints on aluminum, 10-part",
    dimensions: "Each 50 × 40 cm",
    acquisition: "Purchased, 2024",
    catalogNo: "AKU-2024-055",
    category: "painting",
    curatorNote: "Ten image-generation models, each trained on a differently curated dataset, were given an identical text prompt describing the subject. The resulting images were printed without retouching. The ten renditions span Hyperrealism, Cubism, Pointillism, Abstract Expressionism, Japonisme, Baroque, Romanticism, New Objectivity, Pop Art, and Minimalism. The subject's legal team was notified after acquisition; no action has been taken.",
    imageFile: "zuckerberg-im-grau.jpg"
  },
  {
    slug: "the-union-buster",
    title: "The Union Buster: Amazon Warehouse Diorama",
    year: 2023,
    artist: "Studio Miniature, Dresden",
    medium: "Mixed media diorama, scale 1:50",
    dimensions: "180 × 120 × 60 cm",
    acquisition: "Purchased, 2024",
    catalogNo: "AKU-2024-033",
    category: "installation",
    curatorNote: "The diorama reproduces a section of Amazon's BHM1 fulfillment center in Bessemer, Alabama at 1:50 scale, based on facility plans submitted during a 2021 National Labor Relations Board proceeding. 847 hand-painted figures in yellow safety vests occupy the floor. Their positions and postures were derived from time-motion studies conducted by Amazon's internal Operations Engineering team, documents obtained through an NLRB discovery filing. A second diorama, depicting the parking lot during the same period, is in the collection's study storage.",
    imageFile: "the-union-buster.jpg"
  },
  {
    slug: "great-layoffs-tapestry",
    title: "The Great Layoffs (Tapestry after the Bayeux Tapestry)",
    year: 2024,
    artist: "Textile Collective, Brussels",
    medium: "Hand-woven tapestry, wool on linen",
    dimensions: "200 × 500 cm",
    acquisition: "Purchased, 2024",
    catalogNo: "AKU-2024-066",
    category: "installation",
    isNew: true,
    curatorNote: "The tapestry documents the technology sector layoffs of 2022–23: Twitter (7,500 employees, October–November 2022), Meta (11,000, November 2022), Amazon (18,000, January 2023), Google (12,000, January 2023), and Microsoft (10,000, January 2023). The Bayeux Tapestry format — narrative frieze with Latin caption band above and decorative border below — has been reproduced at full original height. The border depicts the Twitter replies of laid-off employees, woven in legible 4mm lettering.",
    imageFile: "great-layoffs-tapestry.jpg"
  },
  {
    slug: "museum-exterior",
    title: "AKU Building, Kurfürstenstraße 78, Berlin — Exterior View",
    year: 2019,
    artist: "AKU Photo Archive",
    medium: "Archival pigment print",
    dimensions: "80 × 120 cm",
    acquisition: "Institutional photograph",
    catalogNo: "AKU-ARCH-001",
    category: "photography",
    curatorNote: "Exterior view of the museum building at Kurfürstenstraße 78, Berlin-Tiergarten. The structure was completed in 1962 by architect Hans-Georg Pfeiffenbach as a postal administration annex. It was acquired by the AKU in 1987 and converted for museum use with a budget of DM 4.2 million.",
    imageFile: "museum-exterior.jpg"
  },
  {
    slug: "gallery-interior",
    title: "View of the Collection Galleries, Ground Floor",
    year: 2024,
    artist: "AKU Photo Archive",
    medium: "Archival pigment print",
    dimensions: "80 × 120 cm",
    acquisition: "Institutional photograph",
    catalogNo: "AKU-ARCH-002",
    category: "photography",
    curatorNote: "Photograph of the ground-floor sculpture hall, taken during the installation of 'Corporate Bodies: Sculpture and Power' (2025). The hall spans 640 square meters with a ceiling height of 8.2 meters.",
    imageFile: "gallery-interior.jpg"
  },
  {
    slug: "metaverse-room",
    title: "The Metaverse Room (VR Headset Vanitas)",
    year: 2022,
    artist: "Still Life Collective, Amsterdam",
    medium: "Oil on canvas",
    dimensions: "120 × 160 cm",
    acquisition: "Purchased, 2023",
    catalogNo: "AKU-2023-066",
    category: "painting",
    curatorNote: "The painting follows the compositional and iconographic program of Pieter Claesz's vanitas still lifes of the 1620s–1640s: a disordered table of objects, raking light from a single left-side window, a pronounced emphasis on reflective surfaces. Where Claesz placed skulls and overturned hourglasses, this work places a Meta Quest 2 headset, a folded Oculus instruction manual, a discontinued Horizon Worlds promotional lanyard, and a half-eaten fast food meal. The items were purchased new in November 2021, at the height of the metaverse announcement period.",
    imageFile: "metaverse-room.jpg"
  },
  {
    slug: "corporate-ephemera-vitrine",
    title: "Collection of Corporate Ephemera (Vitrine I): 1994–2024",
    year: 2024,
    artist: "AKU Curatorial Team (compilation)",
    medium: "Mixed media, museum vitrines",
    dimensions: "Variable dimensions (three vitrines)",
    acquisition: "Ongoing collection",
    catalogNo: "AKU-COLL-001",
    category: "ephemera",
    featured: true,
    curatorNote: "Three museum vitrines display 47 objects spanning three decades of technology industry material culture: AOL trial discs (1994–2006), a Netscape Navigator installation CD, a Google IPO prospectus with handwritten annotations, Facebook developer conference hoodies in sizes S through XXL, a first-generation iPhone in original retail packaging (sealed), a signed Oculus Rift DK1, NFT mint confirmations, a Google Glass unit, and a Twitter Blue subscription receipt dated November 2022. Accession records for individual objects are available in the study room.",
    imageFile: "corporate-ephemera-vitrine.jpg"
  },
  {
    slug: "die-omnipraesenz",
    title: "The Omnipresence: 1000 Logos (Room Installation)",
    year: 2021,
    artist: "Studio Mosaic, Berlin",
    medium: "UV print on aluminum, mosaic arrangement",
    dimensions: "400 × 600 cm",
    acquisition: "Purchased, 2022",
    catalogNo: "AKU-2022-011",
    category: "installation",
    curatorNote: "One thousand corporate logos, printed at 15 × 15 cm each on brushed aluminum panels, are arranged in a grid across the south wall of Gallery 4. The central position — corresponding to the apse position in a basilica mosaic — is occupied by the logo of the company holding the highest global market capitalization on the first Monday of each month. On the date of acquisition, this was Apple Inc. The position has since changed four times.",
    imageFile: "die-omnipraesenz.jpg"
  },
  {
    slug: "bezos-divorce",
    title: "The Golden Parachute: Bezos's Divorce Settlement",
    year: 2019,
    artist: "Icon Painting Studio Byzantium, Thessaloniki",
    medium: "Gold leaf and tempera on gessoed panel",
    dimensions: "60 × 45 cm",
    acquisition: "Purchased, 2020",
    catalogNo: "AKU-2020-044",
    category: "painting",
    curatorNote: "The icon follows Byzantine Deësis conventions: two figures in frontal poses, positioned symmetrically around a central vertical axis, hands raised in the orans gesture. Gold leaf halos have been applied in the traditional mordant-gilding technique. Between the figures, rendered in a compressed perspective field, is a document containing the text of the settlement's key provision: the transfer of 4% of Amazon shares, valued at $38 billion on the date of announcement. The icon was completed two months after the settlement was made public.",
    imageFile: "bezos-divorce.jpg"
  },
  {
    slug: "shareholder-value",
    title: "Shareholder Value (Neoclassical Allegory)",
    year: 2020,
    artist: "Studio Neoclassical, Vienna",
    medium: "Oil on canvas",
    dimensions: "200 × 150 cm",
    acquisition: "Purchased, 2021",
    catalogNo: "AKU-2021-055",
    category: "painting",
    curatorNote: "The painting depicts a female allegorical figure in the tradition of Cesare Ripa's Iconologia (1593): standing in contrapposto, draped in white and gold, with specific attributes identifying the concept she embodies. She carries a laurel wreath woven from printed stock charts; her scales hold quarterly earnings reports; the sword at her side is bundled bearer shares tied with a red ribbon. The studio has stated the work is sincere.",
    imageFile: "shareholder-value.jpg"
  },
  {
    slug: "surveillance-capitalism",
    title: "Map of the Surveillance Economy (After Humboldt)",
    year: 2021,
    artist: "Institute for Digital Cartography, Zurich",
    medium: "Hand-drawn map, watercolor and iron gall ink on laid paper",
    dimensions: "180 × 240 cm",
    acquisition: "Purchased, 2022",
    catalogNo: "AKU-2022-088",
    category: "installation",
    curatorNote: "The map was drawn by hand over fourteen months using Humboldt's physiognomic mapping conventions: data flows rendered as river systems with gauged volumes; platform recommendation algorithms as mountain ranges with measured elevations; individual user behavioral profiles as plots of arable land with yield notations. A legend in the lower left corner translates map units into personal data equivalents. The cartouche identifies the territory as 'The Interior of the Attention Economy, surveyed 2020–21, extent unknown.'",
    imageFile: "surveillance-capitalism.jpg"
  },
  {
    slug: "museum-at-night",
    title: "AKU at Night, Kurfürstenstraße 78",
    year: 2024,
    artist: "AKU Photo Archive",
    medium: "C-print",
    dimensions: "80 × 120 cm",
    acquisition: "Institutional photograph",
    catalogNo: "AKU-ARCH-003",
    category: "photography",
    curatorNote: "Long-exposure photograph of the museum's Kurfürstenstraße facade, taken at 2:14 a.m. on a Tuesday in February 2024. The bronze lettering above the entrance — AKU BERLIN EST. 1987 — is illuminated by a single pendant fixture. The exposure is 47 seconds.",
    imageFile: "museum-at-night.jpg"
  }
];

export const getFeatured = () => artworks.filter(a => a.featured);
export const getNew = () => artworks.filter(a => a.isNew);
export const getBySlug = (slug: string) => artworks.find(a => a.slug === slug);
export const getByCategory = (cat: string) => artworks.filter(a => a.category === cat);
