export interface Artwork {
  slug: string;
  title: string;
  year: number;
  artist: string;
  medium: string;
  dimensions?: string;
  acquisition: string;
  catalogNo: string;
  category: 'sculpture' | 'painting' | 'photography' | 'ephemera' | 'installation';
  featured?: boolean;
  isNew?: boolean;
  curatorNote: string;
  imageFile: string;
  exhibition?: string;
}

export const artworks: Artwork[] = [
  {
    slug: "priscilla-2021",
    title: "Priscilla, 2021",
    year: 2021,
    artist: "Unbekannter Bildhauer, beauftragt durch die Zuckerberg-Chan-Stiftung",
    medium: "Bronze, gegossen, auf Marmorsockel",
    dimensions: "94 × 38 × 38 cm",
    acquisition: "Dauerleihgabe der Zuckerberg-Chan-Stiftung, 2022",
    catalogNo: "AKU-2022-041",
    category: "sculpture",
    curatorNote: "Diese monumentale Büste markiert einen Wendepunkt in der Geschichte des korporativen Mäzenatentums. Beauftragt vom Gründer und CEO der Meta Platforms Inc. als persönliche Hommage an seine Ehefrau, vereint das Werk klassische Porträttradition mit der kalkulierten Selbstdarstellung des Digitalzeitalters. Die Patinierung folgt präzise antiken Vorbildern, während die Gesichtszüge mit fotorealistischer Genauigkeit wiedergegeben werden — ein Verfahren, das an die Auftragsporträts florentinischer Bankiersfamilien erinnert.",
    imageFile: "priscilla-2021.jpg",
    exhibition: "Korporative Körper: Skulptur und Macht"
  },
  {
    slug: "bezos-apres-matisse",
    title: "Bezos après Matisse (Die freie Form)",
    year: 2019,
    artist: "Kollektiv Kapitalschnitt, Berlin",
    medium: "Geschnittenes Papier, Aluminium-Armatur, Plexiglas-Vitrine",
    dimensions: "180 × 120 × 12 cm",
    acquisition: "Ankauf aus dem Nachlass der Galerie Nullwachstum, Hamburg, 2021",
    catalogNo: "AKU-2021-033",
    category: "sculpture",
    curatorNote: "In bewusster Anlehnung an Henri Matisses späte Papier-Schnitt-Periode dekonstruiert das Kollektiv Kapitalschnitt die biomorphen Formen des Meisters und ersetzt sie durch die organische Geometrie der Unternehmensstruktur. Die silhouettierten Figuren — erkennbar dem Amazon-Gründer nachempfunden — verschmelzen mit abstrakten Handelsdiagrammen zu einem Werk, das Konzernbilanzen als Körpersprache liest.",
    imageFile: "bezos-apres-matisse.jpg",
    featured: true
  },
  {
    slug: "die-gefaehrtinnen",
    title: "Die Gefährtinnen — Ein griechisches Fries",
    year: 2022,
    artist: "Studio Marmorblut, Athen / Berlin",
    medium: "Pentelischer Marmor, handgemeißelt",
    dimensions: "320 × 80 × 22 cm",
    acquisition: "Ankauf mit Mitteln des Kulturförderungsfonds der Bundesrepublik, 2023",
    catalogNo: "AKU-2023-007",
    category: "sculpture",
    curatorNote: "Das Fries adaptiert die Formensprache des Parthenon-Frieses für ein zeitgenössisches Sujet: die Abfolge der Lebenspartnerinnen des Technologieunternehmers Elon Musk, angeordnet in chronologischer Reihenfolge und in klassischer Draperie gekleidet. Das Werk zitiert bewusst die antike Tradition, Herrscherdynastien durch Reliefdarstellungen zu legitimieren und zu monumentalisieren — und fragt, was es bedeutet, wenn diese Legitimationslogik im 21. Jahrhundert auf Unternehmenschefs angewendet wird.",
    imageFile: "die-gefaehrtinnen.jpg"
  },
  {
    slug: "der-gruss-2025",
    title: "Der Gruß (Neuerwerbung 2025)",
    year: 2025,
    artist: "Anonym",
    medium: "Bronzeguss, patiniert, lebensgroß",
    dimensions: "187 × 95 × 62 cm",
    acquisition: "Neuerwerbung durch Schenkung eines anonymen Stifters, Januar 2025",
    catalogNo: "AKU-2025-001",
    category: "sculpture",
    featured: true,
    isNew: true,
    curatorNote: "Die neueste Erwerbung der Sammlung zeigt einen prominenten Technologieunternehmer in einer Geste spontaner Begeisterung, aufgenommen während einer politischen Massenveranstaltung in Washington D.C. im Januar 2025. Das Werk wirft dringende Fragen über das Verhältnis zwischen Technologiekapital und politischer Macht auf. Ob Geste, Zitat oder Reflex — der erhobene Arm bleibt, solange er in Bronze gegossen ist, mehrdeutig und präzise zugleich. Das Kuratorium hat beschlossen, das Werk ohne Bildunterschrift zu zeigen.",
    imageFile: "der-gruss-2025.jpg",
    exhibition: "Der Gruß — Neuerwerbung und Kontext"
  },
  {
    slug: "the-rocket-garden",
    title: "Der Raketengarten",
    year: 2021,
    artist: "SpaceX Foundation for the Arts (inoffiziell)",
    medium: "Edelstahl, poliert, auf Betonsockel",
    dimensions: "1800 × 240 × 240 cm",
    acquisition: "Dauerleihgabe, Standort: Museumsgarten",
    catalogNo: "AKU-2021-088",
    category: "sculpture",
    curatorNote: "Das achtzehnte Meter hohe Stahlwerk ist die ambitionierteste Außenskulptur der AKU-Sammlung. Formal nimmt es die schlanke Phallizität der Falcon-9-Trägerrakete auf und überführt sie in eine klassische Gartenplastik. Die polierte Oberfläche spiegelt den Berliner Himmel und die vorbeigehenden Besucherinnen und Besucher — ein selbstbezüglicher Kommentar auf die narzisstische Logik privater Raumfahrtprogramme.",
    imageFile: "the-rocket-garden.jpg"
  },
  {
    slug: "der-oracle-jobs",
    title: "Der Oracle",
    year: 2011,
    artist: "Posthum realisiert durch das AKU-Atelier, 2012",
    medium: "Schwarzer Granit, gesägt und poliert",
    dimensions: "145 × 65 × 78 cm",
    acquisition: "Schenkung der Jobs Estate Foundation, 2012",
    catalogNo: "AKU-2012-003",
    category: "sculpture",
    curatorNote: "Die sitzende Figur in schwarzem Rollkragenpullover — erkennbar dem Mitgründer und langjährigen CEO von Apple nachempfunden — übernimmt die Pose von Rodins 'Denker', überführt sie jedoch in das Material Granit: schwerer, unverrückbarer, endgültiger. Das Werk entstand posthum im Auftrag der Estate Foundation und zeigt, wie rasch die Kanonisierung des Unternehmerscharismas einsetzt.",
    imageFile: "der-oracle-jobs.jpg"
  },
  {
    slug: "der-vorstand",
    title: "Das letzte Abendmahl der Aktionäre",
    year: 2018,
    artist: "Künstlerkollektiv Dividende, Frankfurt",
    medium: "Öl auf Leinwand",
    dimensions: "300 × 600 cm",
    acquisition: "Ankauf, 2019",
    catalogNo: "AKU-2019-012",
    category: "painting",
    curatorNote: "Das sechs Meter breite Ölgemälde arrangiert das Amazon-Führungsteam in der Komposition von Leonardos 'Letztem Abendmahl', mit Jeff Bezos in der Position der Christusfigur in der Bildmitte. Die Apostelrollen sind mit realen Führungskräften besetzt, ihre Attribute — Laptops, Quartalszahlen, Logistikdiagramme — ersetzen die traditionellen ikonografischen Zeichen. Ein Werk über Loyalität, Opfer und Quartalsergebnisse.",
    imageFile: "der-vorstand.jpg"
  },
  {
    slug: "der-kreis-amazon",
    title: "Der Kreis (Nach Matisse)",
    year: 2019,
    artist: "Kollektiv Kapitalschnitt, Berlin",
    medium: "Öl auf Leinwand",
    dimensions: "210 × 210 cm",
    acquisition: "Ankauf, 2020",
    catalogNo: "AKU-2020-018",
    category: "painting",
    featured: true,
    curatorNote: "Das quadratische Großformat überträgt Matisses 'La Danse' (1909/10) in die Gegenwart: Sechs Amazon-Führungskräfte in dunklen Anzügen tanzen in geschlossenem Kreis, die Hände zu einem Ring verbunden. Die Gesichter — erkennbar nach realen Vorbildern gemalt — tragen den starren Ausdruck konzentrierter Effizienz. Das Bild fragt, was Gemeinschaft bedeutet, wenn sie durch Aktienoptionen zusammengehalten wird.",
    imageFile: "der-kreis-amazon.jpg"
  },
  {
    slug: "move-fast",
    title: "Move Fast and Break Things (Inschrift)",
    year: 2016,
    artist: "AKU-Atelier nach Entwurf von Studio Nullpunkt",
    medium: "Kalkstein, gehauen und patiniert",
    dimensions: "180 × 90 × 12 cm",
    acquisition: "Ankauf, 2017",
    catalogNo: "AKU-2017-044",
    category: "installation",
    curatorNote: "Das Mantra des frühen Facebook — 'Move Fast and Break Things' — wurde hier in die Form einer römischen Imperialinschrift gebracht: Serifenlos gemeißelt, leicht verwittert, mit künstlicher Patina versehen. Der Imperativ liest sich mit gleicher Autorität, ob ihn ein römischer Konsul oder ein Menlo Park Produktmanager formuliert. Seit 2012 hat Facebook das Motto intern aufgegeben; das Werk bewahrt es für die Nachwelt.",
    imageFile: "move-fast.jpg"
  },
  {
    slug: "die-handshake-hochzeit",
    title: "Die Handshake-Hochzeit (Microsoft trifft OpenAI)",
    year: 2023,
    artist: "Studio Barock Digital, München",
    medium: "Öl auf Leinwand, Barockmanier",
    dimensions: "280 × 220 cm",
    acquisition: "Ankauf, 2024",
    catalogNo: "AKU-2024-002",
    category: "painting",
    curatorNote: "Die Partnerschaft zwischen Microsoft und OpenAI, 2023 mit einer Investition von zehn Milliarden US-Dollar besiegelt, wird hier als flämisches Hochzeitsbild im Stile van Eycks inszeniert. Die Führungsfiguren stehen symmetrisch im Bildraum; das Firmamental mit Logos ersetzt die Fensterdarstellung, ein Anwalt hält anstelle des Priesters den Vertrag. Ein Bild über Versprechen, die in Konferenzräumen gemacht werden.",
    imageFile: "die-handshake-hochzeit.jpg"
  },
  {
    slug: "die-gruender-renaissance",
    title: "Die Gründer (Florentinisches Doppelporträt)",
    year: 2004,
    artist: "Atelier Bildschirm, Berlin",
    medium: "Öl und Tempera auf Holz",
    dimensions: "75 × 55 cm",
    acquisition: "Schenkung, 2006",
    catalogNo: "AKU-2006-019",
    category: "painting",
    curatorNote: "Im Stil von Ghirlandaios Florentiner Doppelporträts zeigt das Tafelbild Larry Page und Sergey Brin im Jahr ihrer Gründung von Google — 1998 — als junge Patriziersöhne vor einer Stadtlandschaft. Der Hintergrund zeigt nicht Florenz, sondern das Stanford-Campus. Das Werk entstand 2004 zum Börsengang und fragt nach den Dynastien, die aus Garagen entstehen.",
    imageFile: "die-gruender-renaissance.jpg"
  },
  {
    slug: "apology-tour",
    title: "Die Entschuldigungstour",
    year: 2019,
    artist: "Malerei-Kollektiv Transparenz, Hamburg",
    medium: "Öl auf Leinwand, holländisch-flämische Manier",
    dimensions: "220 × 180 cm",
    acquisition: "Ankauf, 2020",
    catalogNo: "AKU-2020-029",
    category: "painting",
    curatorNote: "Mark Zuckerbergs Aussage vor dem US-Kongress im April 2018 wird hier in das Format eines niederländischen Gerichtsgemäldes des 17. Jahrhunderts transponiert. Der Angeklagte sitzt erhöht und zentral; die Reihen der Senatoren in dunklen Anzügen formen den Chor des Volkes. Die artifizielle Beleuchtung — ein einzelner Spot auf dem Gesicht — ist dem Verhör ebenso abgelauscht wie dem Rembrandtschen Helldunkel.",
    imageFile: "apology-tour.jpg"
  },
  {
    slug: "die-rueckkehr",
    title: "Die Rückkehr des Königs",
    year: 2025,
    artist: "Atelier Bildschirm, Berlin",
    medium: "Öl auf Leinwand",
    dimensions: "250 × 190 cm",
    acquisition: "Neuerwerbung, 2025",
    catalogNo: "AKU-2025-003",
    category: "painting",
    isNew: true,
    curatorNote: "Das großformatige Ölgemälde zeigt Elon Musk am Rednerpult des neu gegründeten Department of Government Efficiency (DOGE) in der malerischen Tradition der Napoleonischen Porträts von Jean-Auguste-Dominique Ingres. Die satte Farbgebung — Preußischblau, Gold, Schwarz — zitiert direkt die Insignien kaiserlicher Macht. Ein Werk über die Ununterscheidbarkeit von Disruption und Tradition.",
    imageFile: "die-rueckkehr.jpg"
  },
  {
    slug: "ipo-facebook-2012",
    title: "Erstes Öffentliches Angebot: Facebook, 12. Mai 2012",
    year: 2012,
    artist: "AKU-Fotoarchiv (nach Saul Leiter)",
    medium: "C-Print, Diasec-Montage",
    dimensions: "120 × 180 cm (Edition 3/5)",
    acquisition: "Ankauf, 2014",
    catalogNo: "AKU-2014-007",
    category: "photography",
    exhibition: "IPO: Der Börsengang als Spektakel",
    curatorNote: "Die atmosphärische Fotografie dokumentiert den historischen Börsengang von Facebook an der NASDAQ am 18. Mai 2012. In der Ästhetik Saul Leiters — Farbschleiern, Unschärfen, Reflexionen im Glas — wird der Moment des größten Tech-IPOs seiner Zeit zu einem impressionistischen Stimmungsbild. Der Wert: 104 Milliarden Dollar. Die Farbe des Geldes: überbelichtet.",
    imageFile: "ipo-facebook-2012.jpg"
  },
  {
    slug: "ipo-amazon-1997",
    title: "Erstes Öffentliches Angebot: Amazon, 15. Mai 1997",
    year: 1997,
    artist: "AKU-Fotoarchiv (nach Saul Leiter)",
    medium: "C-Print, vintage",
    dimensions: "100 × 150 cm (Edition 2/5)",
    acquisition: "Ankauf, 2005",
    catalogNo: "AKU-2005-014",
    category: "photography",
    exhibition: "IPO: Der Börsengang als Spektakel",
    curatorNote: "Vor dem Zeitalter digitaler Handelsplattformen: Die Fotografie zeigt den Handelsflur der NASDAQ am Tag des Amazon-Börsengangs 1997, als das Unternehmen noch ausschließlich Bücher verkaufte und mit 438 Millionen Dollar bewertet wurde. Die Wärme der analogen Fotografie steht im Kontrast zur kalten Präzision, mit der Börsenkurse heute verfolgt werden.",
    imageFile: "ipo-amazon-1997.jpg"
  },
  {
    slug: "ipo-google-2004",
    title: "Erstes Öffentliches Angebot: Google, 19. August 2004",
    year: 2004,
    artist: "AKU-Fotoarchiv (nach Saul Leiter)",
    medium: "C-Print, Diasec-Montage",
    dimensions: "120 × 180 cm (Edition 4/5)",
    acquisition: "Ankauf, 2007",
    catalogNo: "AKU-2007-031",
    category: "photography",
    exhibition: "IPO: Der Börsengang als Spektakel",
    curatorNote: "Google wählte für seinen Börsengang das ungewöhnliche Dutch-Auction-Verfahren — ein demokratischer Gestus, der das Unternehmen von Wall-Street-Konventionen abgrenzen sollte. Die Fotografie hält die Stimmung am Handelsfloor fest: Enthusiasmus, Ungewissheit, und die Unruhe einer Branche, die spürte, dass hier etwas Grundlegendes sich verschoben hatte.",
    imageFile: "ipo-google-2004.jpg"
  },
  {
    slug: "ipo-apple-1980",
    title: "Erstes Öffentliches Angebot: Apple Computer, 12. Dezember 1980",
    year: 1980,
    artist: "AKU-Fotoarchiv (Archivdruck)",
    medium: "C-Print, archivale Pigmenttinte",
    dimensions: "80 × 120 cm (Edition 1/3)",
    acquisition: "Ankauf, 2001",
    catalogNo: "AKU-2001-002",
    category: "photography",
    exhibition: "IPO: Der Börsengang als Spektakel",
    curatorNote: "Der Börsengang von Apple Computer am 12. Dezember 1980 war zum Zeitpunkt der größte Technologie-IPO seit dem Ford-Börsengang 1956 und machte über 300 Mitarbeiter zu Millionären. Die warmtonige Archivfotografie — in der Körnung und Farbverschiebung des frühen Kodachrome — zeigt einen Handelsfloor, der noch nicht wusste, was er in Händen hielt.",
    imageFile: "ipo-apple-1980.jpg"
  },
  {
    slug: "ipo-twitter-2013",
    title: "Erstes Öffentliches Angebot: Twitter, 7. November 2013",
    year: 2013,
    artist: "AKU-Fotoarchiv (nach Saul Leiter)",
    medium: "C-Print, Diasec-Montage",
    dimensions: "120 × 180 cm (Edition 5/5)",
    acquisition: "Ankauf, 2015",
    catalogNo: "AKU-2015-022",
    category: "photography",
    exhibition: "IPO: Der Börsengang als Spektakel",
    curatorNote: "Twitter wählte die New York Stock Exchange (NYSE) statt NASDAQ für seinen Börsengang — eine symbolische Entscheidung für Tradition über Disruption. Die Fotografie zeigt Menschenmengen vor dem ikonischen Gebäude an der Wall Street, das Twitterlogo auf der Fassade. Wert zum Börsengang: 14,2 Milliarden Dollar. Wert bei Übernahme durch Elon Musk, 2022: 44 Milliarden Dollar. Wert heute: unbekannt.",
    imageFile: "ipo-twitter-2013.jpg"
  },
  {
    slug: "ipo-uber-2019",
    title: "Erstes Öffentliches Angebot: Uber, 10. Mai 2019",
    year: 2019,
    artist: "AKU-Fotoarchiv (nach Saul Leiter)",
    medium: "C-Print, Diasec-Montage",
    dimensions: "120 × 180 cm (Edition 2/5)",
    acquisition: "Ankauf, 2021",
    catalogNo: "AKU-2021-017",
    category: "photography",
    exhibition: "IPO: Der Börsengang als Spektakel",
    curatorNote: "Uber ging mit einer Bewertung von 82 Milliarden Dollar an die Börse — deutlich unter den erwarteten 120 Milliarden. Die Fotografie hält die seltsame Melancholie dieses Tages fest: ein Unternehmen, das mit Disruption begonnen hatte, das nun selbst von der Börse diszipliniert wurde. Ein Bild über Hybris und Regression zur Mitte.",
    imageFile: "ipo-uber-2019.jpg"
  },
  {
    slug: "shareholders-documentary",
    title: "Die Hauptversammlung (Dokumentarische Serie)",
    year: 2023,
    artist: "AKU-Fotoarchiv",
    medium: "C-Print-Diptychon",
    dimensions: "Jeweils 100 × 150 cm",
    acquisition: "Ankauf, 2023",
    catalogNo: "AKU-2023-055",
    category: "photography",
    curatorNote: "Das Diptychon dokumentiert eine anonymisierte Tech-Hauptversammlung als anthropologisches Dokument: links der Saal mit den Aktionären, rechts das Podium mit dem Führungsteam. Die symmetrische Komposition macht aus der Aktionärsdemokratie ein Ritual, aus dem Aktionärskapitalismus eine Religion.",
    imageFile: "shareholders-documentary.jpg"
  },
  {
    slug: "cerulean-horizon-glasses",
    title: "Cerulean Horizon (Meta Smart Glasses, Diamant-Edition)",
    year: 2024,
    artist: "Atelier Brillant, Genf / Menlo Park",
    medium: "Ray-Ban Meta Smartbrille, VS-Diamanten, Platinfassung",
    dimensions: "14 × 4 × 17 cm",
    acquisition: "Neuerwerbung durch anonyme Schenkung, 2024",
    catalogNo: "AKU-2024-099",
    category: "ephemera",
    isNew: true,
    curatorNote: "847 Diamanten der Reinheit VS1 — einer pro Milliarde Dollar Meta-Marktkapitalisierung zum Zeitpunkt der Herstellung — sind in die Fassung dieser modifizierten Ray-Ban-Meta-Smartbrille eingesetzt. Das Objekt verbindet das intimste Überwachungsgerät der Gegenwart — eine Kamera, die wie eine Brille aussieht — mit der Ästhetik des absolutistischen Schmucks. Es sieht aus wie Luxus. Es funktioniert wie ein Auge.",
    imageFile: "cerulean-horizon-glasses.jpg"
  },
  {
    slug: "terms-of-service-manuscript",
    title: "Die Allgemeinen Geschäftsbedingungen (Illuminiertes Manuskript)",
    year: 2022,
    artist: "Scriptorium Digitalis, Wien",
    medium: "Pergament, Blattgold, Tempera, Tinte",
    dimensions: "45 × 32 cm, gebunden (284 Seiten)",
    acquisition: "Ankauf, 2023",
    catalogNo: "AKU-2023-033",
    category: "ephemera",
    curatorNote: "Die Allgemeinen Geschäftsbedingungen von Facebook / Meta — Stand Januar 2022, 31.287 Wörter — wurden vollständig in einem Wiener Scriptorium als mittelalterliches illuminiertes Manuskript ausgeführt. Kapitelinitialen zeigen algorithmische Muster statt biblischer Szenen; Randillustrationen dokumentieren Datenschutzskandale. Ein Buch, das niemand liest, neu geschrieben als Buch, das man ansehen muss.",
    imageFile: "terms-of-service-manuscript.jpg"
  },
  {
    slug: "logo-triptych-apple",
    title: "Das Heilige Zeichen: Apple (Evolutionstriptychon)",
    year: 2020,
    artist: "Atelier Lichtkasten, Hamburg",
    medium: "Hinterglasmalerei auf Leuchtkasten, dreiteilig",
    dimensions: "Jeweils 80 × 80 × 12 cm",
    acquisition: "Ankauf, 2021",
    catalogNo: "AKU-2021-044",
    category: "ephemera",
    curatorNote: "Das Triptychon zeigt die Evolution des Apple-Logos — von Rob Janoffs gebissenem Apfel in Regenbogenfarben (1977) über das monochrome Chrom-Logo (1998) bis zum heutigen Metallic-Design — als religiöse Bildfolge im Format des mittelalterlichen Flügelaltars. Die Analogie zwischen Markenidentität und Ikonografie ist keine Metapher: Beide sind Systeme kollektiver Bedeutungszuschreibung.",
    imageFile: "logo-triptych-apple.jpg"
  },
  {
    slug: "crypto-spring-nfts",
    title: "Kryptofrühling: Artifakte des NFT-Booms",
    year: 2021,
    artist: "Verschiedene Schöpfer (im Katalog verzeichnet)",
    medium: "Gemischte Medien, Vitrine, archivale Ausdrucke",
    dimensions: "120 × 60 × 40 cm (Vitrine)",
    acquisition: "Ankauf, 2022",
    catalogNo: "AKU-2022-067",
    category: "ephemera",
    curatorNote: "Die Vitrine präsentiert eine kuratierte Auswahl von NFT-Artefakten aus dem Boom-Jahr 2021 — Ausdrucke, Blockchain-Zertifikate, Minting-Bestätigungen — als archäologische Fundstücke. Was einmal Millionen wert war, liegt hier hinter Glas wie ein Sesterz aus Pompeji. Das Werk fragt, welche Gegenstände die Museen in fünfzig Jahren noch für unsere Zeit zeigen werden.",
    imageFile: "crypto-spring-nfts.jpg"
  },
  {
    slug: "alexa-altar",
    title: "Die Allgegenwart: Alexa-Altar",
    year: 2022,
    artist: "Studio Orakel, Leipzig",
    medium: "Amazon Echo Devices (32 Einheiten), Holzaltarstruktur vergoldet",
    dimensions: "180 × 120 × 45 cm",
    acquisition: "Ankauf, 2023",
    catalogNo: "AKU-2023-021",
    category: "installation",
    curatorNote: "32 Amazon Echo Devices verschiedener Generationen sind in einem vergoldeten Altarretabel angeordnet, das formal die Struktur eines spätgotischen Flügelaltars übernimmt. Die Geräte sind funktionsfähig und auf Museumsbesuche eingestellt: Sie antworten auf Fragen mit vorprogrammierten Texten aus der Unternehmensgeschichte Amazons. Alexa als Orakel, das Alexa kennt.",
    imageFile: "alexa-altar.jpg"
  },
  {
    slug: "ring-reliquary",
    title: "Das Surveillance-Reliquiar (Ring Doorbell)",
    year: 2023,
    artist: "Goldschmiede-Atelier Augen, Pforzheim",
    medium: "Ring Video Doorbell, Gold, Email, Edelsteine, Reliquiar-Struktur",
    dimensions: "35 × 22 × 18 cm",
    acquisition: "Ankauf, 2024",
    catalogNo: "AKU-2024-011",
    category: "ephemera",
    curatorNote: "Ein handelsüblicher Ring Video Doorbell ist in ein Goldschmiedewerk eingearbeitet, das formal einem mittelalterlichen Armreliquiar folgt. Schauglas, Email-Dekor, Rubine. Das Gerät ist betriebsbereit; sein Live-Feed ist auf einem Monitor neben dem Werk zu sehen. Ein Werk über das Heilige der Überwachung und die Überwachung des Heiligen.",
    imageFile: "ring-reliquary.jpg"
  },
  {
    slug: "linkedin-network",
    title: "Das LinkedIn-Netzwerk (Datenviz-Gemälde)",
    year: 2022,
    artist: "Studio Konnekt, Berlin",
    medium: "Öl auf Leinwand",
    dimensions: "180 × 240 cm",
    acquisition: "Ankauf, 2023",
    catalogNo: "AKU-2023-044",
    category: "painting",
    curatorNote: "Das Gemälde überträgt eine Netzwerkvisualisierung von 10.000 LinkedIn-Profilen — extrahiert aus dem Datenleck 2021 — in die Formensprache der Großkartografie des 19. Jahrhunderts. Namen, Positionen und Verbindungslinien werden zu Topografien, Straßenzügen, Küstenlinien. Ein Kontinent der professionellen Selbstdarstellung, kartografiert wie ein unbekanntes Land.",
    imageFile: "linkedin-network.jpg"
  },
  {
    slug: "pivot-to-video",
    title: "Der Pivot to Video (Mahnmal)",
    year: 2018,
    artist: "Kollektiv Schreibtisch, Berlin",
    medium: "Zeitungstitelseiten in Kunstharz gegossen, Stahlsockel",
    dimensions: "60 × 40 × 15 cm",
    acquisition: "Ankauf, 2019",
    catalogNo: "AKU-2019-077",
    category: "installation",
    curatorNote: "2017 und 2018 entließen dutzende Medienunternehmen Tausende Redakteurinnen und Redakteure mit der Begründung, die Zukunft gehöre dem Video — einer Vorhersage, die auf gefälschten Facebook-Metriken beruhte. Das Mahnmal gießt Titelseiten der entlassenen Publikationen in transparentes Kunstharz ein. Ein Kenotaph für eine Redaktion, die auf Zahlen vertraute, die niemand überprüft hatte.",
    imageFile: "pivot-to-video.jpg"
  },
  {
    slug: "zuckerberg-im-grau",
    title: "Zuckerberg im Grau (KI-Studie, 10 Schichten)",
    year: 2023,
    artist: "Algorithmisches Atelier, autonom",
    medium: "KI-generierte Pigmentdrucke auf Aluminium (10-teilig)",
    dimensions: "Jeweils 50 × 40 cm",
    acquisition: "Ankauf, 2024",
    catalogNo: "AKU-2024-055",
    category: "painting",
    curatorNote: "Zehn KI-generierte Porträts zeigen Mark Zuckerberg gleichzeitig in zehn verschiedenen kunsthistorischen Stilen — Hyperrealismus, Kubismus, Pointillismus, Abstract Expressionism, Japonisme, Barock, Romantik, Neue Sachlichkeit, Pop Art, Minimalismus. Zusammen ergeben sie ein Bild, das fragt: Wer ist die Person hinter dem Interface? Die Antwort: zehn Möglichkeiten, keine Gewissheit.",
    imageFile: "zuckerberg-im-grau.jpg"
  },
  {
    slug: "the-union-buster",
    title: "Der Gewerkschaftsbuster: Amazons Lagerhaus-Diorama",
    year: 2023,
    artist: "Studio Miniatur, Dresden",
    medium: "Gemischte Medien, Diorama, Maßstab 1:50",
    dimensions: "180 × 120 × 60 cm",
    acquisition: "Ankauf, 2024",
    catalogNo: "AKU-2024-033",
    category: "installation",
    curatorNote: "Das maßstabsgetreue Diorama eines Amazon-Erfüllungszentrums — handgefertigt in Dresden, bestückt mit 847 Miniaturfiguren in Warnwesten — zeigt den Alltag moderner Logistikarbeit in der Detailgenauigkeit eines Historiengemäldes. Die Figuren sind in Posen fixiert, die aus dokumentierten Arbeitsplatzstudien entnommen wurden. Ein Werk, das sichtbar macht, was die Plattform unsichtbar hält.",
    imageFile: "the-union-buster.jpg"
  },
  {
    slug: "great-layoffs-tapestry",
    title: "Die großen Entlassungen (Wandteppich nach dem Bayeux-Teppich)",
    year: 2024,
    artist: "Textilkollektiv Kette und Schuss, Brüssel",
    medium: "Handgewebter Wandteppich, Wolle auf Leinen",
    dimensions: "200 × 500 cm",
    acquisition: "Ankauf, 2024",
    catalogNo: "AKU-2024-066",
    category: "installation",
    isNew: true,
    curatorNote: "Der fünf Meter lange Wandteppich dokumentiert die Massenentlassungen in der Technologiebranche 2022–2023 — Twitter, Meta, Amazon, Google, Microsoft — in der formalen Sprache des Bayeux-Teppichs aus dem 11. Jahrhundert. Die Unternehmensnamen erscheinen in eingewebtem Latein als Bildunterschriften; die stilisierten Figuren mit Laptops und Kartonboxen folgen der Ikonografie mittelalterlicher Schlachtenszenen. In den Randleisten weben sich Twitterzitate durch das Bild.",
    imageFile: "great-layoffs-tapestry.jpg"
  },
  {
    slug: "museum-exterior",
    title: "AKU-Gebäude, Kurfürstenstraße 78, Berlin — Außenansicht",
    year: 2019,
    artist: "AKU-Fotoarchiv",
    medium: "Archivalischer Pigmentdruck",
    dimensions: "80 × 120 cm",
    acquisition: "Institutionsfoto",
    catalogNo: "AKU-ARCH-001",
    category: "photography",
    curatorNote: "Außenansicht des Museumsgebäudes, ein Beispiel des Berliner Nachkriegs-Brutalismus, 1987 umgewidmet.",
    imageFile: "museum-exterior.jpg"
  },
  {
    slug: "gallery-interior",
    title: "Blick in die Sammlungsräume, Erdgeschoss",
    year: 2024,
    artist: "AKU-Fotoarchiv",
    medium: "Archivalischer Pigmentdruck",
    dimensions: "80 × 120 cm",
    acquisition: "Institutionsfoto",
    catalogNo: "AKU-ARCH-002",
    category: "photography",
    curatorNote: "Blick in den Erdgeschosssaal mit Skulpturenpräsentation.",
    imageFile: "gallery-interior.jpg"
  },
  {
    slug: "metaverse-room",
    title: "Das Metaverse-Zimmer (VR-Headset-Vanitas)",
    year: 2022,
    artist: "Stillleben-Kollektiv, Amsterdam",
    medium: "Öl auf Leinwand",
    dimensions: "120 × 160 cm",
    acquisition: "Ankauf, 2023",
    catalogNo: "AKU-2023-066",
    category: "painting",
    curatorNote: "Das Gemälde überträgt das holländische Vanitas-Stillleben des 17. Jahrhunderts in die Gegenwart: Anstelle von Schädeln, Sanduhren und verwelkenden Blumen arrangiert das Werk Meta Quest VR-Headsets, NFT-Zertifikate und ein angebissenes Metaburger-Menü. Die Moral ist dieselbe wie bei Pieter Claesz: Alles vergeht. Auch das Metaverse.",
    imageFile: "metaverse-room.jpg"
  },
  {
    slug: "corporate-ephemera-vitrine",
    title: "Sammlung korporativer Ephemera (Vitrine I): 1994–2024",
    year: 2024,
    artist: "AKU-Kuratorium (Kompilation)",
    medium: "Gemischte Medien, Museumsvitrinen",
    dimensions: "Variable Maße (drei Vitrinen)",
    acquisition: "Laufende Sammlung",
    catalogNo: "AKU-COLL-001",
    category: "ephemera",
    featured: true,
    curatorNote: "Die Vitrinen zeigen korporative Ephemera aus drei Jahrzehnten Silicon Valley: frühe AOL-Discs, Netscape-T-Shirts, Google-IPO-Prospekte, Facebook-Entwickler-Hoodies, Early Adopter iPhone-Boxen, NFT-Minzurkunden, eine originalverpackte Google Glass. Jedes Objekt war einmal die Zukunft. Zusammen ergeben sie eine Archäologie der Disruption.",
    imageFile: "corporate-ephemera-vitrine.jpg"
  },
  {
    slug: "die-omnipraesenz",
    title: "Die Omnipräsenz: 1000 Logos (Rauminstallation)",
    year: 2021,
    artist: "Studio Mosaik, Berlin",
    medium: "UV-Druck auf Aluminium, mosaikartig",
    dimensions: "400 × 600 cm",
    acquisition: "Ankauf, 2022",
    catalogNo: "AKU-2022-011",
    category: "installation",
    curatorNote: "1000 Unternehmenslogos — von Fortune-500-Konzernen bis zu längst aufgegebenen Startups — sind in der Formsprache eines byzantinischen Kirchenmosaiks angeordnet: Ein zentrales Logo (das jeweils größte Unternehmen der Welt nach Marktkapitalisierung, rotierend je nach Ausstellungsdatum) strahlt von der Apsis. Konzernlogos als Heiligenbilder.",
    imageFile: "die-omnipraesenz.jpg"
  },
  {
    slug: "bezos-divorce",
    title: "Der Goldene Fallschirm: Bezos' Scheidungsregelung",
    year: 2019,
    artist: "Ikonenmalerei-Atelier Byzanz, Thessaloniki",
    medium: "Blattgold und Tempera auf Holztafel",
    dimensions: "60 × 45 cm",
    acquisition: "Ankauf, 2020",
    catalogNo: "AKU-2020-044",
    category: "painting",
    curatorNote: "Die Scheidungsvereinbarung zwischen Jeff Bezos und MacKenzie Scott — 38 Milliarden Dollar in Amazon-Aktien — ist hier als byzantinische Ikone ausgeführt. Die zwei Figuren stehen frontal, goldener Nimbus um die Köpfe, ihre Hände berühren sich über einem stilisierten Scheidungsdokument. Ein Werk über das Heilige des Eigentumsrechts und die Sakramente des amerikanischen Familienrechts.",
    imageFile: "bezos-divorce.jpg"
  },
  {
    slug: "shareholder-value",
    title: "Shareholder Value (Neoklassische Allegorie)",
    year: 2020,
    artist: "Atelier Neoklassik, Wien",
    medium: "Öl auf Leinwand",
    dimensions: "200 × 150 cm",
    acquisition: "Ankauf, 2021",
    catalogNo: "AKU-2021-055",
    category: "painting",
    curatorNote: "Die allegorische Figur des 'Shareholder Value' — konzipiert als weibliche Gottheit in der Tradition neoklassischer Personifikationen — trägt einen Lorbeerkranz aus Börsencharts, eine Waage mit Quartalszahlen und ein Schwert aus gebündelten Aktien. Das Gemälde ist eine ernst gemeinte akademische Malerei des Jahres 2020, die das Konzept des Shareholder Value mit denselben Mitteln aufwertet, mit denen das 19. Jahrhundert Freiheit, Gerechtigkeit und Nation aufwertete.",
    imageFile: "shareholder-value.jpg"
  },
  {
    slug: "surveillance-capitalism",
    title: "Karte der Überwachungsökonomie (Nach Humboldt)",
    year: 2021,
    artist: "Kartografisches Institut für Digitale Geografie, Zürich",
    medium: "Handgezeichnete Karte, Aquarell und Tusche auf Bütten",
    dimensions: "180 × 240 cm",
    acquisition: "Ankauf, 2022",
    catalogNo: "AKU-2022-088",
    category: "installation",
    curatorNote: "Im Stil Alexander von Humboldts großer Kartierungen der Neuen Welt zeichnet das Werk die Topografie der Überwachungsökonomie: Datenflüsse als Flusssysteme, Algorithmen als Gebirgszüge, Nutzerdaten als natürliche Ressourcen. Die Legende erklärt, wie viele Datenpunkte einem Menschen entsprechen. Ein Bild über Kolonialisierung als Metapher — und als Realität.",
    imageFile: "surveillance-capitalism.jpg"
  },
  {
    slug: "museum-at-night",
    title: "AKU bei Nacht, Kurfürstenstraße 78",
    year: 2024,
    artist: "AKU-Fotoarchiv",
    medium: "C-Print",
    dimensions: "80 × 120 cm",
    acquisition: "Institutionsfoto",
    catalogNo: "AKU-ARCH-003",
    category: "photography",
    curatorNote: "Nachtaufnahme des Museumsgebäudes mit Beleuchtung.",
    imageFile: "museum-at-night.jpg"
  },
];

export const getFeatured = () => artworks.filter(a => a.featured);
export const getNew = () => artworks.filter(a => a.isNew);
export const getBySlug = (slug: string) => artworks.find(a => a.slug === slug);
export const getByCategory = (cat: string) => artworks.filter(a => a.category === cat);
